enum OrderType {
    MONEY = 0,
    CREDIT = 1,
    DEBIT = 2,
}

enum OrderStatus {
    TO_FINISH = 0,
    MADE = 1,
    PREPARING = 2,
    SENDING = 3,
    SENDED = 4,
    CANCELED = 5,
}

enum OrderUserWhoDeleted {
    BACKOFFICE = 0,
    CLIENT = 1,
}

const priceByDistrict = {
    brasiliaTeimosa: 6,
    cabanga: 6,
    boaViagem: 6,
    pina: 6,
    setubal: 6,
    imbiribeira: 6,
    boaVista: 9,
    madalena: 9,
    ipsep: 9,
    derby: 9,
    gracas: 9,
    bairroDoRecife: 9,
    soledade: 9,
    paissandu: 9,
    ibura: 9,
    ilhaDoLeite: 9,
    ilhaDoRetiro: 9,
    saoJose: 9,
    jordaoDeRecife: 9,
    benfica: 9,
    espinheiro: 12,
    rosarinho: 12,
    areias: 12,
    encruzilhada: 12,
    afogados: 12,
    jardimSaoPaulo: 12,
    aflitos: 12,
    torre: 12,
    torreao: 12,
    varzea: 12,
    bongi: 12,
    macaxeira: 12,
    novaDescoberta: 12,
    piedade: 12,
    candeias: 12,
    santaTereza: 12,
    bairroNovo: 12,
    hipodromo: 12,
    sanMartin: 12,
    apipucos: 16,
    aguaFria: 16,
    arruda: 16,
    caxanga: 16,
    doisIrmaos: 16,
    cidadeUniversitaria: 16,
    parnamirim: 16,
    casaForte: 16,
    casaAmarela: 16,
    pocoDaPanela: 16,
    iputinga: 16,
    engenhoDoMeio: 16,
    portoDaMadeira: 16,
    peixinhos: 16,
    tamarineira: 16,
    tejipio: 16,
}

export { OrderType, OrderStatus, OrderUserWhoDeleted, priceByDistrict }